apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runnerdeploy
  labels:
    Runner: {{ .Values.runner }}
spec:
  replicas: 1
  template:
    spec:
      repository: {{ .Values.repository }}